---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# evworkplace

<!-- badges: start -->
<!-- badges: end -->

The goal of evworkplace is to make it easy to estimate workplace charging demand for an EV adoption scenario produced using the stocked package. Charging demand is estimated using a simplified version of the model developed in Chakraborty, D., Bunch, D. S., Lee, J. H., & Tal, G. (2019) "Demand drivers for charging infrastructure-charging behavior of plug-in electric vehicle commuters." in *Transportation Research Part D: Transport and Environment*. This paper can be found [here](http://www.sciencedirect.com/science/article/pii/S1361920919301919).

## Installation

You can install the development version of this package from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("davisadamw/evworkplace")
```

Installing this package should install the required package [stocked](https://github.com/davisadamw/stocked) automatically, but if not it can be installed with:
``` r
devtools::install_github("davisadamw/stocked")
```

## TODOs
* Simplify the commute assignment component so that it's small enough to fit in the package
* Identify key charging parameters to provide access to, lock the rest in place
* Finally, convert events to kWh

## Example

_in progress_

